# Generated by Django 3.2.4 on 2021-06-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=400, verbose_name='вариант ответа')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200, verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип вопроса')),
            ],
            options={
                'verbose_name': 'тип вопроса',
                'verbose_name_plural': 'типы вопросов',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_dt', models.DateTimeField(auto_now=True)),
                ('quest_end_dt', models.DateTimeField(verbose_name='Дата окончания опроса')),
                ('quest_name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('quest_description', models.TextField(max_length=600, verbose_name='Описание опроса')),
                ('issue_questionaire', models.ManyToManyField(to='myapi.Issue', verbose_name='вопрос опросника')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.issuetype', verbose_name='тип вопроса'),
        ),
        migrations.AddField(
            model_name='issue',
            name='variants',
            field=models.ManyToManyField(to='myapi.AnswerVariant', verbose_name='вариант ответа'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=400, null=True, verbose_name='ответ')),
                ('issue_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.issue', verbose_name='вопрос')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
