# Generated by Django 3.2.4 on 2021-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='myapi.AnswerVariant', verbose_name='вариант ответа'),
        ),
    ]
