# Generated by Django 3.2.4 on 2021-06-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200, verbose_name='вопрос')),
                ('issue_questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.questionnaire', verbose_name='вопрос опросника')),
            ],
        ),
    ]
