# Generated by Django 3.2.4 on 2021-06-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='тип вопроса'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_questionaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.questionnaire', verbose_name='вопрос опросника'),
        ),
    ]
