# Generated by Django 3.2.4 on 2021-06-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_issue_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='issue_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.answer', verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='variants',
            field=models.ManyToManyField(blank=True, to='myapi.AnswerVariant', verbose_name='вариант ответа'),
        ),
    ]
