# Generated by Django 3.2.4 on 2021-06-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210603_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип вопроса')),
            ],
            options={
                'verbose_name': 'тип вопроса',
                'verbose_name_plural': 'типы вопросов',
            },
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.issuetype', verbose_name='тип вопроса'),
        ),
    ]
