# Generated by Django 3.2.4 on 2021-06-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210619_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.issue', verbose_name='вопрос'),
        ),
    ]
